version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "2345:5432"
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

  backend:
    build: ./backend
    container_name: "backend"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend